name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on:  self-hosted                      #ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]  # herewe are setting it to execute with different versions of python so we are going to be seeing two jobs runing

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2    # here is installing plugins 
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py
